//! # About Hypersynthetic
//!
//! Hypersynthetic is a library for writing HTML inside Rust.
//! It is inspired by JSX and HEEx templates, and tries to be different from Tera and Minijinja
//! by enabling [Locality of Behavior (LoB)](https://htmx.org/essays/locality-of-behaviour/)
//! and only allowing reusing HTML code via composition and not via inheritance.
//! It is suitable for building traditional web applications, where backend responds with HTML.
//!
//! Here is an example of what hypersynthetic can do:
//!
//! ```
//! use hypersynthetic::prelude::*;
//!
//! #[component]
//! fn TodoItem(text: &str, done: bool) -> HtmlFragment {
//!     let text_decoration = if done { "line-through" } else { "none" };
//!
//!     html! {
//!         <li style="text-decoration: {text_decoration};">
//!             {text}
//!         </li>
//!     }
//! }
//!
//! fn main() {
//!     let todo_list = vec![
//!         ("Buy Milk", true),
//!         ("Read Rust Book", false),
//!         ("Write Web App using html! macro", false),
//!     ];
//!
//!     let html_list = html! {
//!         <ul>
//!             <TodoItem :for={(text, done) in todo_list} text={text} done={done} />
//!         </ul>
//!     };
//!
//!     // ... Render `html_list` into your application.
//!     assert_eq!(html_list.to_string(),  "\
//!         <ul>\
//!             <li style=\"text-decoration: line-through;\">Buy Milk</li>\
//!             <li style=\"text-decoration: none;\">Read Rust Book</li>\
//!             <li style=\"text-decoration: none;\">Write Web App using html! macro</li>\
//!         </ul>"
//!     );
//! }
//! ```
//!
//! In this example:
//!
//! The TodoItem component displays a to-do item, striking it through if it's done.
//! The main function defines a list of to-dos and uses the :for attribute to loop over them,
//! rendering each one using the TodoItem component.
//!
//! See the [html] macro for the description of the syntax and [component](macro@component) macro for more details about using components
//!
//! ## Features
//!
//! - `rocket`: Enables integration with the Rocket web framework. It allows to return [HtmlFragment] from the route handlers and sets the response content type to `text/html`.
//! - `axum`: Enables integration with the Axum web framework. It allows to return [HtmlFragment] from the route handlers and sets the response content type to `text/html`.

#![warn(missing_docs)]

pub use class_list::{ClassList, ClassListMut};
pub use htmlize::{escape_attribute, escape_text};
pub use search::Descendants;

mod class_list;
mod search;

pub mod component;

#[doc(hidden)]
pub mod __private;

/// The component macro provides a way to define reusable and self-contained web components.
/// A component is a function that returns a [HtmlFragment]. The easiest way to create one is
/// [html] macro.
///
/// # Basic Usage
///
/// ```
/// # use hypersynthetic::prelude::*;
/// #[component]
/// fn MyComponent(prop1: &str, prop2: i32) -> HtmlFragment {
///    html! {
///        <div>
///            <p>{prop1}</p>
///            <p>{prop2}</p>
///        </div>
///    }
/// }
///
/// // ...
///
/// # fn main() {
/// let html = html! {
///     <MyComponent prop1="Hello" prop2={42} />
/// };
/// # }
/// ```
///
/// A component name must start with an uppercase letter and it must return a [HtmlFragment].
///
/// **Note:** Components are designed to be used exclusively within the [html] macro using
/// the `<Component />` syntax. Direct function calls (e.g., `MyComponent(...)`) are not
/// supported.
///
/// # Props
/// Components accept properties, similar to function arguments.
/// These properties can be any Rust type, providing a type-safe way to pass data to components.
/// When calling a component from [html] macro, the properties are passed as html arguments.
/// The arguments can be in any order, it's not necessary for them to be in the same order as defined in the component function.
///
/// ## Optional props
/// Props are set through a builder generated by [typed_builder](https://docs.rs/typed-builder),
/// and a `#[builder(...)]` attribute on a parameter configures its setter.
/// `default` makes a prop optional, and `setter(into)` accepts anything that converts into its type:
/// ```
/// # use hypersynthetic::prelude::*;
/// #[component]
/// fn Badge(
///     text: &str,
///     #[builder(default = "info".to_owned(), setter(into))] kind: String,
///     #[builder(default)] count: u32,
/// ) -> HtmlFragment {
///     html! { <span class="badge {kind}">{text}" "{count}</span> }
/// }
///
/// # fn main() {
/// let html = html! {
///     <Badge text="New" />
///     <Badge text="Errors" kind="danger" count={3} />
/// };
/// assert_eq!(
///     html.to_string(),
///     r#"<span class="badge info">New 0</span><span class="badge danger">Errors 3</span>"#
/// );
/// # }
/// ```
///
/// ## Boolean props
/// Like boolean attributes in HTML, a prop written without a value is `true`:
/// `<Button disabled />` is short for `<Button disabled={true} />`.
/// ```
/// # use hypersynthetic::prelude::*;
/// #[component]
/// fn Button(text: &str, #[builder(default)] disabled: bool) -> HtmlFragment {
///     html! { <button :if={!disabled}>{text}</button> }
/// }
///
/// # fn main() {
/// let html = html! {
///     <Button text="Save" />
///     <Button text="Delete" disabled />
/// };
/// assert_eq!(html.to_string(), "<button>Save</button>");
/// # }
/// ```
///
/// # Children
///
/// The content between a component's tags is passed to its parameter named `children`,
/// which must be an [HtmlFragment]. It can be anywhere in the parameter list.
///
/// ```
/// # use hypersynthetic::prelude::*;
/// #[component]
/// fn OrangeDiv(children: HtmlFragment) -> HtmlFragment {
///     html! {
///         <div class="orange round">{children}</div>
///     }
/// }
///
/// # fn main() {
/// let data = "Hello, world!";
/// let result = html! {
///     <OrangeDiv>
///         <p>{ data }</p>
///     </OrangeDiv>
/// };
///
/// assert_eq!(
///     result.to_string(),
///     r#"<div class="orange round"><p>Hello, world!</p></div>"#
/// );
/// # }
/// ```
///
/// `children` is a prop like any other, with two differences:
///
/// - The content between the tags is passed as `children`, and an existing fragment can
///   also be passed as an attribute: `<OrangeDiv children={content} />`. Giving both is a
///   compile error.
/// - It's optional: without content or a `children` attribute, it's an empty fragment.
///
/// ```
/// # use hypersynthetic::prelude::*;
/// # #[component]
/// # fn OrangeDiv(children: HtmlFragment) -> HtmlFragment {
/// #     html! { <div class="orange round">{children}</div> }
/// # }
/// # fn main() {
/// let content = html! { <p>"Hello"</p> };
/// let result = html! {
///     <OrangeDiv><p>"Hello"</p></OrangeDiv>
///     <OrangeDiv children={content} />
///     <OrangeDiv />
/// };
///
/// assert_eq!(
///     result.to_string(),
///     "<div class=\"orange round\"><p>Hello</p></div>\
///      <div class=\"orange round\"><p>Hello</p></div>\
///      <div class=\"orange round\"></div>"
/// );
/// # }
/// ```
///
/// Other [HtmlFragment] parameters are ordinary props, so a component can take several
/// pieces of HTML:
///
/// ```
/// # use hypersynthetic::prelude::*;
/// #[component]
/// fn Page(header: HtmlFragment, children: HtmlFragment) -> HtmlFragment {
///     html! { <header>{header}</header><main>{children}</main> }
/// }
///
/// # fn main() {
/// let page = html! {
///     <Page header={html! { <h1>"Title"</h1> }}>
///         <p>"Text"</p>
///     </Page>
/// };
/// assert_eq!(
///     page.to_string(),
///     "<header><h1>Title</h1></header><main><p>Text</p></main>"
/// );
/// # }
/// ```
///
/// Content between the tags of a component without a `children` parameter is a compile
/// error: "no method named `children` found for struct `CardPropsBuilder`". If a component
/// accepts children but doesn't use them, keep the name `children` and add
/// `#[allow(unused_variables)]` to the parameter: `_children` wouldn't receive them.
///
/// `children` is only special for components. On HTML elements, `<div children="...">`
/// is an ordinary attribute.
pub use hypersynthetic_macros::component;

/// The `html` macro allows to construct html fragments in Rust.
/// It mostly follows the same syntax as HTML with the following exceptions:
///
/// 1. Void tags need to be self-closing. For example `<br>` should be written as `<br />`.
///
/// 2. Bare text is not (yet) allowed. Instead you should put a string literal inside an expression
///    like `<span>{"text"}</span>`. Alternatively, for convenience, you can use the string literal
///    directly like `<span>"text"</span>`. But the latter syntax is likely to change in the future.
///    See this [github issue](https://github.com/sanchopanca/hypersynthetic/issues/3) for details.
///
/// With gotchas out the way, here are the features:
///
/// # Dynamic content
/// An expression that implements Display trait (or just ToString trait) inside curly braces (`{expression}`)
/// will be substituted with the result of .to_string() call, applying html escaping.
/// To avoid escaping, wrap the expression in double curly braces: `{{expression}}` (not available in string literals,
/// see an example below).
///
/// An [HtmlFragment] is inserted as HTML in both cases, so templates can be composed:
/// ```
/// # use hypersynthetic::html;
/// let item = html! { <b>"bold"</b> };
/// let list = html! {
///     <p>{item}</p>
/// };
/// assert_eq!(list.to_string(), "<p><b>bold</b></p>");
/// ```
///
/// An [Option] renders the value inside `Some` the same way, and nothing for `None`:
/// ```
/// # use hypersynthetic::html;
/// let subtitle: Option<&str> = None;
/// let badge = Some(html! { <b>"new"</b> });
/// let header = html! {
///     <h1>"Title"{badge}</h1>
///     <h2>{subtitle}</h2>
/// };
/// assert_eq!(header.to_string(), "<h1>Title<b>new</b></h1><h2></h2>");
/// ```
///
/// Here are the places where an expression can be used:
/// 1. As a child of an element.
/// ```
/// # use hypersynthetic::html;
/// let txt = "Text";
/// let div = html! {
///     <div>{txt}</div>
/// };
/// assert_eq!(div.to_string(), "<div>Text</div>");
///
/// let span = html! {
///     <span>{txt}{txt}</span>
/// };
/// assert_eq!(span.to_string(), "<span>TextText</span>");
/// ```
///
/// 2. In an attribute value or its part.
/// ```
/// # use hypersynthetic::html;
/// let cls = "header";
/// let div = html! {
///     <div class={cls}>{"Breaking news"}</div>
/// };
/// assert_eq!(div.to_string(), r#"<div class="header">Breaking news</div>"#);
///
/// let id = 42;
/// let span = html! {
///     <span id="header-{id}">{"Breaking news"}</span>
/// };
///
/// assert_eq!(span.to_string(), r#"<span id="header-42">Breaking news</span>"#);
/// ```
///
/// An [Option] value leaves the attribute out when it's `None`:
/// ```
/// # use hypersynthetic::html;
/// let title: Option<&str> = None;
/// let link = html! { <a href="/" title={title}>"Home"</a> };
/// assert_eq!(link.to_string(), r#"<a href="/">Home</a>"#);
/// ```
///
/// HTML boolean attributes like `disabled`, `checked` or `hidden` are on whenever
/// they're present, even as `disabled="false"`. So on them, a [bool] value decides whether
/// the attribute is there. On other attributes, a `bool` is written as `"true"` or `"false"`,
/// which is what `aria-expanded` or htmx's `hx-boost` expect:
/// ```
/// # use hypersynthetic::html;
/// let busy = false;
/// let open = false;
/// let button = html! {
///     <button disabled={busy} aria-expanded={open}>"Menu"</button>
/// };
/// assert_eq!(button.to_string(), r#"<button aria-expanded="false">Menu</button>"#);
/// ```
/// For boolean attributes of custom elements, which hypersynthetic doesn't know about,
/// use an `Option`: `my-flag={on.then_some("")}`.
///
/// 3. In an attribute name.
/// ```
/// # use hypersynthetic::html;
/// let method = "hx-get";
/// let div = html! {
///     <button {method}="/resources">{"Get 'em"}</button>
/// };
/// assert_eq!(div.to_string(), r#"<button hx-get="/resources">Get 'em</button>"#);
/// ```
///
/// Attribute names aren't escaped. Instead, an attribute whose name isn't valid HTML
/// (empty, or containing whitespace, control characters or any of `"'<>/=`) is not rendered.
/// ```
/// # use hypersynthetic::html;
/// let name = "x onclick=alert(1)";
/// let div = html! {
///     <div {name}="v" class="c"></div>
/// };
/// assert_eq!(div.to_string(), r#"<div class="c"></div>"#);
/// ```
///
/// 4. In a string literal.
/// ```
/// # use hypersynthetic::html;
/// let txt = "Hello";
/// let div = html! {
///     <div>"{txt} World"</div>
/// };
/// assert_eq!(div.to_string(), "<div>Hello World</div>");
/// ```
///
/// In string literals, both in text and in attribute values, the braces can contain
/// any expression, optionally followed by a [`format!`] spec:
/// ```
/// # use hypersynthetic::html;
/// struct Item { name: &'static str, price: f64 }
/// let item = Item { name: "Tea", price: 2.5 };
/// let p = html! {
///     <p data-price="{item.price:.2}">"{item.name}: {item.price:.2}"</p>
/// };
/// assert_eq!(p.to_string(), r#"<p data-price="2.50">Tea: 2.50</p>"#);
/// ```
///
/// ## Disabling escaping
/// To disable escaping, use double curly braces: `{{expression}}`.
/// ```
/// # use hypersynthetic::html;
/// let txt = "<span>I know what I'm doing</span>";
/// let div = html! {
///     <div>{{txt}}</div>
/// };
/// assert_eq!(div.to_string(), "<div><span>I know what I'm doing</span></div>");
/// ```
/// ### Disabling escaping doesn't work in string literals
/// Under the hood, hypersynthetic uses Rust built-in `format!` function which uses {{ and }} to escape { and }.
/// So this is what happens if you use double curly braces in a string literal:
/// ```
/// # use hypersynthetic::html;
/// let txt = "Hello";
/// let div = html! {
///     <div>"{{txt}} World"</div>
/// };
/// assert_eq!(div.to_string(), "<div>{txt} World</div>");
/// ```
///
/// The same rule applies in attribute values, which is how to write literal braces
/// there, e.g. for Alpine.js or htmx:
/// ```
/// # use hypersynthetic::html;
/// let count = 5;
/// let div = html! {
///     <div x-data="{{ open: false, count: {count} }}"></div>
/// };
/// assert_eq!(div.to_string(), r#"<div x-data="{ open: false, count: 5 }"></div>"#);
/// ```
///
/// # `<script>` and `<style>`
/// The content of these elements is JavaScript and CSS, not HTML: browsers don't decode
/// `&lt;` or `&amp;` there. So string literals in them are rendered as written, without
/// escaping (braces are still written `{{` and `}}`):
/// ```
/// # use hypersynthetic::html;
/// let style = html! {
///     <style>"a > b {{ color: red; }}"</style>
/// };
/// assert_eq!(style.to_string(), "<style>a > b { color: red; }</style>");
/// ```
///
/// HTML escaping can't make a value safe inside JavaScript or CSS, so `{expression}`,
/// and `{expression}` inside a string literal, are compile errors there. Insert values
/// unescaped with `{{expression}}`, after making sure they can't contain `</script>`
/// (or `</style>`):
/// ```
/// # use hypersynthetic::html;
/// let count = 5;
/// let script = html! {
///     <script>"let count = "{{count}}";"</script>
/// };
/// assert_eq!(script.to_string(), "<script>let count = 5;</script>");
/// ```
/// ```compile_fail
/// # use hypersynthetic::html;
/// let count = 5;
/// let script = html! {
///     <script>"let count = {count};"</script> // error: `<script>` content isn't HTML
/// };
/// ```
///
/// # Conditionals
/// A special pseudo-attribute `:if` is used to conditionally render an element.
/// ```
/// # use hypersynthetic::html;
/// let notify_user = true;
/// let div = html! {
///     <div :if={notify_user}>
///         <span>"You have been warned"</span>
///     </div>
/// };
/// assert_eq!(div.to_string(), "<div><span>You have been warned</span></div>");
///
/// let notify_user = false;
/// let div = html! {
///     <div :if={notify_user}>
///         <span>"You have been warned"</span>
///     </div>
/// };
/// assert_eq!(div.to_string(), "");
/// ```
///
/// To emulate `else` branch, reverse the condition:
/// ```
/// # use hypersynthetic::html;
/// let notify_user = false;
/// let div = html! {
///     <div :if={notify_user}>
///         <span>"Be careful"</span>
///     </div>
///     <div :if={!notify_user}>
///         <span>"You are safe"</span>
///     </div>
/// };
/// assert_eq!(div.to_string(), "<div><span>You are safe</span></div>");
/// ```
///
/// # Iteration
/// A special pseudo-attribute `:for` is used to iterate over an iterable object and create an element for each item.
/// ```
/// # use hypersynthetic::html;
/// let numbers = [1, 2];
/// let div = html! {
///     <div :for={n in numbers}>
///         <span>{n}</span>
///     </div>
/// };
/// assert_eq!(div.to_string(), "<div><span>1</span></div><div><span>2</span></div>");
///
/// let div = html! {
///     <input :for={n in numbers} type="text" value={n} />
/// };
/// assert_eq!(div.to_string(), r#"<input type="text" value="1" /><input type="text" value="2" />"#);
/// ```
///
/// Fragments can also be built in Rust code and collected into one:
/// ```
/// # use hypersynthetic::prelude::*;
/// let items = ["a", "b"];
/// let list: HtmlFragment = items.iter().map(|item| html! { <li>{item}</li> }).collect();
/// let ul = html! { <ul>{list}</ul> };
/// assert_eq!(ul.to_string(), "<ul><li>a</li><li>b</li></ul>");
/// ```
///
/// ## `:if` together with `:for`
/// When an element has both, `:if` is checked once, before the loop: it decides
/// whether the loop runs at all.
/// ```
/// # use hypersynthetic::html;
/// let show_list = false;
/// let items = html! {
///     <li :if={show_list} :for={n in [1, 2]}>{n}</li>
/// };
/// assert_eq!(items.to_string(), "");
/// ```
///
/// So the condition can't use the loop variable:
/// ```compile_fail
/// # use hypersynthetic::html;
/// let items = html! {
///     <li :for={n in [1, 2, 3, 4]} :if={n % 2 == 0}>{n}</li> // error: cannot find value `n`
/// };
/// ```
///
/// To skip some items, filter the iterator instead:
/// ```
/// # use hypersynthetic::html;
/// let items = html! {
///     <li :for={n in [1, 2, 3, 4].into_iter().filter(|n| n % 2 == 0)}>{n}</li>
/// };
/// assert_eq!(items.to_string(), "<li>2</li><li>4</li>");
/// ```
///
/// # Components
/// Components can be called as tags. Here is an example:
/// ```
/// # use hypersynthetic::prelude::*;
/// #[component]
/// fn MyDiv(text: &str) -> HtmlFragment {
///     html! {
///         <div>{text}</div>
///     }
/// }
/// fn main() {
///     let div = html! {
///         <div>
///             <MyDiv text="my text" />
///         </div>
///     };    
/// }
/// ```
/// See [component](macro@component) macro for more details.
pub use hypersynthetic_macros::html;

/// Everything needed to write templates and components: `use hypersynthetic::prelude::*;`
pub mod prelude {
    pub use crate::HtmlFragment;
    pub use crate::component::{Component, Props};
    pub use crate::{component, html};
}

use std::borrow::Cow;
use std::fmt;
use std::slice::Iter;
use std::slice::IterMut;
use std::sync::Arc;

/// A sequence of HTML nodes, as produced by [html!].
///
/// Build fragments with [html!], [HtmlFragment::new], `From<Vec<Node>>` or `collect()`,
/// and read or change them with [HtmlFragment::child_nodes],
/// [HtmlFragment::child_nodes_mut] or [HtmlFragment::iter_elements].
///
/// Cloning is cheap: the nodes are shared until one of the copies is changed, and only
/// then copied (copy-on-write). So inserting a fragment into another one with
/// `{fragment}` doesn't copy everything below it.
///
/// # Compared to the DOM
///
/// Fragments and elements work like a simplified DOM, with the same names in snake_case
/// where an operation means the same thing:
///
/// | DOM | hypersynthetic |
/// |---|---|
/// | `childNodes` | [child_nodes()](HtmlFragment::child_nodes), a slice |
/// | `firstChild`, `lastChild` | `child_nodes().first()`, `child_nodes().last()` |
/// | `children` (elements only) | [iter_elements()](HtmlFragment::iter_elements) |
/// | `append()`, `appendChild()` | [push()](HtmlFragment::push), [add_child()](ElementData::add_child), `extend()` |
/// | `prepend()`, `insertBefore()` | [child_nodes_mut()](HtmlFragment::child_nodes_mut)`.insert(index, node)` |
/// | `removeChild()` | `child_nodes_mut().remove(index)` or `.retain(…)` |
/// | `replaceChildren()` | `*child_nodes_mut() = nodes` |
/// | `tagName` | [tag_name](ElementData::tag_name) |
/// | `getAttribute()`, `setAttribute()`, `hasAttribute()`, `removeAttribute()` | [get_attribute()](ElementData::get_attribute), [set_attribute()](ElementData::set_attribute), [has_attribute()](ElementData::has_attribute), [remove_attribute()](ElementData::remove_attribute) |
/// | `toggleAttribute()`, `getAttributeNames()` | [toggle_attribute()](ElementData::toggle_attribute), [get_attribute_names()](ElementData::get_attribute_names) |
/// | `id` | [id()](ElementData::id), `None` when missing |
/// | `classList` | [class_list()](ElementData::class_list) to read, [class_list_mut()](ElementData::class_list_mut) to change |
/// | `getElementById()` | [get_element_by_id()](HtmlFragment::get_element_by_id), [get_element_by_id_mut()](HtmlFragment::get_element_by_id_mut) |
/// | `getElementsByTagName()`, `getElementsByClassName()` | [get_elements_by_tag_name()](HtmlFragment::get_elements_by_tag_name), [get_elements_by_class_name()](HtmlFragment::get_elements_by_class_name): iterators, not live lists |
/// | walking the tree (`TreeWalker`, `querySelectorAll("*")`) | [descendants()](HtmlFragment::descendants), and [for_each_descendant_mut()](HtmlFragment::for_each_descendant_mut) to change elements |
/// | `outerHTML`, `innerHTML` | `to_string()`, `element.children.to_string()` |
/// | `parentNode`, `nextSibling`, `remove()` | none: nodes don't know their parent, so change the tree from the parent |
///
/// Note that [ElementData::children] is the DOM's `childNodes` (text included), not its
/// `children` (elements only).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HtmlFragment(Arc<Vec<Node>>);

/// A node in an [HtmlFragment].
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Node {
    /// An element with its attributes and children, like `<p class="x">...</p>`.
    Element(ElementData),
    /// Text that is written to the output as is. [html!] escapes text before storing it
    /// here; when creating a `Text` node yourself, escape untrusted input with
    /// [escape_text]. Like names in [ElementData], it's a [Cow]: text written in a
    /// template is borrowed, so create one with `Node::Text("…".into())` or
    /// `Node::Text(string.into())`.
    Text(Cow<'static, str>),
    /// `<!DOCTYPE html>`.
    DocType,
}

/// An HTML element: `<tag_name attributes...>children</tag_name>`.
///
/// Names and values are [Cow]s: the ones written in a template are borrowed
/// `&'static str`s, so they aren't copied every time the template runs, and the
/// ones computed at runtime are owned `String`s.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ElementData {
    /// The element's name, like `div` or `my-widget`. If it isn't a valid tag name
    /// (it must start with an ASCII letter and can't contain whitespace, `/`, `>`, `<`,
    /// `=`, quotes or control characters), the element isn't rendered, children
    /// included, since the name could inject markup.
    pub tag_name: Cow<'static, str>,
    /// The attributes, in the order they are rendered.
    pub attributes: Vec<Attribute>,
    /// The nodes between the opening and the closing tag: the DOM's `childNodes`, text
    /// included, not its `children`, which are only the elements.
    pub children: HtmlFragment,
    /// Written as `<tag />`. Only void elements (`br`, `img`, `input`, ...) are rendered
    /// that way; other elements get a closing tag, since browsers ignore `/>` on them.
    pub self_closing: bool,
}

/// An HTML attribute. The value is stored as is, not HTML-escaped: it's escaped when
/// the element is rendered.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Attribute {
    /// The attribute's name. A name that isn't valid HTML is left out when rendering.
    pub name: Cow<'static, str>,
    /// `None` for an attribute without a value, like `disabled`.
    pub value: Option<Cow<'static, str>>,
}

impl HtmlFragment {
    /// A fragment containing `nodes`.
    pub fn new(nodes: Vec<Node>) -> Self {
        HtmlFragment(Arc::new(nodes))
    }

    /// The top-level nodes: the DOM's `childNodes`.
    pub fn child_nodes(&self) -> &[Node] {
        &self.0
    }

    /// The top-level nodes, to change them with `Vec`'s methods: `insert` for the DOM's
    /// `insertBefore()` and `prepend()`, `remove` or `retain` for `removeChild()`, or
    /// assign a new `Vec` for `replaceChildren()`.
    ///
    /// If the nodes are shared with a clone of the fragment, they're copied first, so
    /// the clone doesn't change.
    pub fn child_nodes_mut(&mut self) -> &mut Vec<Node> {
        Arc::make_mut(&mut self.0)
    }

    /// Appends a node at the end.
    pub fn push(&mut self, node: Node) {
        self.child_nodes_mut().push(node);
    }

    /// The number of top-level nodes.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Whether the fragment has no nodes.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// A copy of the top-level nodes.
    #[deprecated(
        note = "use `child_nodes()` to read the nodes, `child_nodes().to_vec()` for a copy, \
                or `into_nodes()` if the fragment isn't needed anymore"
    )]
    pub fn get_nodes(&self) -> Vec<Node> {
        self.child_nodes().to_vec()
    }

    /// The top-level nodes, taken out of the fragment. They're copied only if the
    /// fragment shares them with a clone.
    pub fn into_nodes(self) -> Vec<Node> {
        Arc::unwrap_or_clone(self.0)
    }

    /// Iterates over the top-level nodes.
    pub fn iter(&self) -> Iter<'_, Node> {
        self.0.iter()
    }

    /// Iterates over the top-level nodes, mutably.
    pub fn iter_mut(&mut self) -> IterMut<'_, Node> {
        self.child_nodes_mut().iter_mut()
    }

    /// Iterates over the top-level elements, skipping text and doctype nodes. It doesn't
    /// descend into children; use [ElementData::children] for that.
    pub fn iter_elements(&self) -> ElementDataIter<'_> {
        ElementDataIter { iter: self.iter() }
    }

    /// Like [HtmlFragment::iter_elements], but mutable, e.g. to change attributes.
    pub fn iter_elements_mut(&mut self) -> ElementDataIterMut<'_> {
        ElementDataIterMut {
            iter: self.iter_mut(),
        }
    }
}

/// An empty fragment.
impl Default for HtmlFragment {
    fn default() -> Self {
        HtmlFragment::new(Vec::new())
    }
}

impl From<Vec<Node>> for HtmlFragment {
    fn from(nodes: Vec<Node>) -> Self {
        HtmlFragment::new(nodes)
    }
}

impl FromIterator<Node> for HtmlFragment {
    fn from_iter<I: IntoIterator<Item = Node>>(nodes: I) -> Self {
        HtmlFragment::new(nodes.into_iter().collect())
    }
}

/// Concatenates fragments: `items.iter().map(|item| html! { ... }).collect()`.
impl FromIterator<HtmlFragment> for HtmlFragment {
    fn from_iter<I: IntoIterator<Item = HtmlFragment>>(fragments: I) -> Self {
        fragments.into_iter().flatten().collect()
    }
}

impl Extend<Node> for HtmlFragment {
    fn extend<I: IntoIterator<Item = Node>>(&mut self, nodes: I) {
        self.child_nodes_mut().extend(nodes);
    }
}

impl IntoIterator for HtmlFragment {
    type Item = Node;
    type IntoIter = std::vec::IntoIter<Node>;

    fn into_iter(self) -> Self::IntoIter {
        self.into_nodes().into_iter()
    }
}

impl<'a> IntoIterator for &'a HtmlFragment {
    type Item = &'a Node;
    type IntoIter = Iter<'a, Node>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl<'a> IntoIterator for &'a mut HtmlFragment {
    type Item = &'a mut Node;
    type IntoIter = IterMut<'a, Node>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter_mut()
    }
}

impl ElementData {
    /// An element without attributes or children. The name can be a `&'static str` or
    /// a `String`.
    pub fn new(tag_name: impl Into<Cow<'static, str>>) -> Self {
        ElementData {
            tag_name: tag_name.into(),
            attributes: Vec::new(),
            children: HtmlFragment::new(Vec::new()),
            self_closing: false,
        }
    }

    /// Appends a node to the children.
    pub fn add_child(&mut self, child: Node) {
        self.children.push(child);
    }

    /// The nodes between the opening and the closing tag: the DOM's `childNodes`. See
    /// [HtmlFragment::child_nodes].
    pub fn child_nodes(&self) -> &[Node] {
        self.children.child_nodes()
    }

    /// The nodes between the opening and the closing tag, to change them. See
    /// [HtmlFragment::child_nodes_mut].
    pub fn child_nodes_mut(&mut self) -> &mut Vec<Node> {
        self.children.child_nodes_mut()
    }

    /// Whether the element has an attribute with this name.
    pub fn has_attribute(&self, name: &str) -> bool {
        self.attributes.iter().any(|attr| attr.name == name)
    }

    /// Sets the attribute's value, adding the attribute if it doesn't exist. The value
    /// is escaped when rendered, so pass it unescaped.
    /// Like the DOM's `setAttribute`, an existing attribute keeps its position.
    /// Duplicates of it are removed, since browsers only use the first one.
    /// The name and the value can be `&'static str`s or `String`s.
    pub fn set_attribute(
        &mut self,
        name: impl Into<Cow<'static, str>>,
        value: impl Into<Cow<'static, str>>,
    ) {
        let name = name.into();
        // Moved into the first matching attribute; still `Some` afterwards if there was none
        let mut value = Some(value.into());
        self.attributes.retain_mut(|attr| {
            if attr.name != name {
                return true;
            }
            match value.take() {
                Some(value) => {
                    attr.value = Some(value);
                    true
                }
                None => false,
            }
        });
        if let Some(value) = value {
            self.attributes.push(Attribute {
                name,
                value: Some(value),
            });
        }
    }

    /// Removes all attributes with this name.
    pub fn remove_attribute(&mut self, name: &str) {
        self.attributes.retain(|attr| attr.name != name);
    }

    /// The attribute's value, unescaped. An attribute without a value (`disabled`)
    /// gives an empty string.
    pub fn get_attribute(&self, name: &str) -> Option<&str> {
        self.attributes
            .iter()
            .find(|attr| attr.name == name)
            .map(|attr| attr.value.as_deref().unwrap_or(""))
    }

    /// The attributes' names, in order: the DOM's `getAttributeNames()`.
    pub fn get_attribute_names(&self) -> impl Iterator<Item = &str> {
        self.attributes.iter().map(|attr| &*attr.name)
    }

    /// Adds the attribute (without a value, like `disabled`) if it's missing, and
    /// removes it if it's there; with `force`, only adds (`Some(true)`) or only removes
    /// (`Some(false)`). Returns whether the element has the attribute afterwards. Like
    /// the DOM's `toggleAttribute()`.
    pub fn toggle_attribute(
        &mut self,
        name: impl Into<Cow<'static, str>>,
        force: Option<bool>,
    ) -> bool {
        let name = name.into();
        if self.has_attribute(&name) {
            if force != Some(true) {
                self.remove_attribute(&name);
                return false;
            }
            true
        } else {
            if force != Some(false) {
                self.attributes.push(Attribute { name, value: None });
                return true;
            }
            false
        }
    }

    /// The `id` attribute, if there is one. Like the DOM's `id`, but `None` instead of
    /// an empty string when it's missing.
    pub fn id(&self) -> Option<&str> {
        self.get_attribute("id")
    }

    /// The element's classes, to read them: the DOM's `classList`. See [ClassList].
    pub fn class_list(&self) -> ClassList<'_> {
        ClassList::new(self)
    }

    /// The element's classes, to change them: the DOM's `classList`, with `add`,
    /// `remove`, `toggle` and `replace`. See [ClassListMut].
    ///
    /// ```
    /// # use hypersynthetic::ElementData;
    /// let mut button = ElementData::new("button");
    /// button.class_list_mut().add("btn").add("primary");
    /// assert_eq!(button.get_attribute("class"), Some("btn primary"));
    /// ```
    pub fn class_list_mut(&mut self) -> ClassListMut<'_> {
        ClassListMut::new(self)
    }
}

/// The ASCII bytes allowed in tag and attribute names: not controls, whitespace,
/// DEL, `/`, `>`, `<`, `=` or quotes. Bytes 0x80 and above are allowed here: in UTF-8,
/// every byte of a non-ASCII character is 0x80 or above, so it can't be mistaken for
/// one of these. Names are checked for every element on every render, so it's a
/// table built at compile time: one load per byte.
const NAME_BYTES: [bool; 256] = {
    let mut allowed = [true; 256];
    // Controls and whitespace (0x00 to space), then DEL and the characters above
    let mut byte = 0;
    while byte <= b' ' {
        allowed[byte as usize] = false;
        byte += 1;
    }
    let rejected = [0x7f, b'/', b'>', b'<', b'=', b'"', b'\''];
    let mut i = 0;
    while i < rejected.len() {
        allowed[rejected[i] as usize] = false;
        i += 1;
    }
    allowed
};

/// Tag names start with an ASCII letter, and end at whitespace, `/` or `>`. The
/// other characters rejected here (`<`, `=`, quotes, controls) don't end a name, but
/// are never intended and could confuse other parsers.
/// See <https://html.spec.whatwg.org/multipage/parsing.html#tag-name-state>.
fn is_valid_tag_name(name: &str) -> bool {
    name.as_bytes().first().is_some_and(u8::is_ascii_alphabetic)
        && name.bytes().all(|byte| NAME_BYTES[byte as usize])
}

/// Attribute names are one or more characters other than controls, space,
/// `"`, `'`, `>`, `/`, `=` and noncharacters. `<` is also rejected: the parser
/// tolerates it, but it is a parse error and never intended.
/// See <https://html.spec.whatwg.org/multipage/syntax.html#attributes-2>.
///
/// The ASCII rules are the [NAME_BYTES] table. Non-ASCII controls (U+0080 to
/// U+009F) and noncharacters need the characters decoded, which only names
/// with non-ASCII characters pay for.
fn is_valid_attribute_name(name: &str) -> bool {
    let is_noncharacter =
        |c: char| matches!(c, '\u{FDD0}'..='\u{FDEF}') || (c as u32 & 0xFFFE) == 0xFFFE;

    !name.is_empty()
        && name.bytes().all(|byte| NAME_BYTES[byte as usize])
        && (name.is_ascii() || !name.chars().any(|c| c.is_control() || is_noncharacter(c)))
}

/// Elements that can't have children, so they have no end tag.
/// See <https://html.spec.whatwg.org/multipage/syntax.html#void-elements>.
fn is_void_element(tag_name: &str) -> bool {
    const VOID_ELEMENTS: [&str; 13] = [
        "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source",
        "track", "wbr",
    ];
    VOID_ELEMENTS
        .iter()
        .any(|void| void.eq_ignore_ascii_case(tag_name))
}

/// Attributes that are on whenever they're present, whatever their value: a `bool`
/// value decides whether they're rendered.
/// See <https://html.spec.whatwg.org/multipage/indices.html#attributes-3>.
pub(crate) fn is_boolean_attribute(name: &str) -> bool {
    const BOOLEAN_ATTRIBUTES: [&str; 28] = [
        "allowfullscreen",
        "async",
        "autofocus",
        "autoplay",
        "checked",
        "controls",
        "default",
        "defer",
        "disabled",
        "formnovalidate",
        "hidden",
        "inert",
        "ismap",
        "itemscope",
        "loop",
        "multiple",
        "muted",
        "nomodule",
        "novalidate",
        "open",
        "playsinline",
        "readonly",
        "required",
        "reversed",
        "selected",
        "shadowrootclonable",
        "shadowrootdelegatesfocus",
        "shadowrootserializable",
    ];
    BOOLEAN_ATTRIBUTES
        .iter()
        .any(|boolean| boolean.eq_ignore_ascii_case(name))
}

/// Iterator returned by [HtmlFragment::iter_elements].
pub struct ElementDataIter<'a> {
    iter: Iter<'a, Node>,
}

impl<'a> Iterator for ElementDataIter<'a> {
    type Item = &'a ElementData;

    fn next(&mut self) -> Option<Self::Item> {
        for node in self.iter.by_ref() {
            if let Node::Element(element_data) = node {
                return Some(element_data);
            }
        }
        None
    }
}

/// Iterator returned by [HtmlFragment::iter_elements_mut].
pub struct ElementDataIterMut<'a> {
    iter: IterMut<'a, Node>,
}

impl<'a> Iterator for ElementDataIterMut<'a> {
    type Item = &'a mut ElementData;

    fn next(&mut self) -> Option<Self::Item> {
        for node in self.iter.by_ref() {
            if let Node::Element(element_data) = node {
                return Some(element_data);
            }
        }
        None
    }
}

// Rendering writes straight into the formatter, passing it down to the children,
// so the output is built in one buffer instead of a String per nesting level.

impl fmt::Display for ElementData {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // A name from user data (`ElementData::new(name)`) that isn't valid HTML
        // could inject markup, and an element can't be rendered without its name,
        // so the whole element is skipped, like an invalid attribute.
        if !is_valid_tag_name(&self.tag_name) {
            return Ok(());
        }
        write!(f, "<{}", self.tag_name)?;
        // Names can come from user data (`<div {name}="v">`). A name that isn't
        // valid HTML could close the tag or start a new attribute, and can't be
        // rendered safely, so it is skipped.
        for attr in &self.attributes {
            if !is_valid_attribute_name(&attr.name) {
                continue;
            }
            match &attr.value {
                Some(value) => {
                    write!(f, " {}=\"{}\"", attr.name, escape_attribute(value.as_ref()))?
                }
                None => write!(f, " {}", attr.name)?,
            }
        }

        // `/>` is only meaningful on void elements: browsers ignore it on
        // other tags and treat `<div />` as an unclosed `<div>`.
        if self.self_closing && is_void_element(&self.tag_name) {
            return f.write_str(" />");
        }

        f.write_str(">")?;
        fmt::Display::fmt(&self.children, f)?;
        write!(f, "</{}>", self.tag_name)
    }
}

impl fmt::Display for Node {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Node::Text(text) => f.write_str(text),
            Node::Element(element_data) => fmt::Display::fmt(element_data, f),
            Node::DocType => f.write_str("<!DOCTYPE html>"),
        }
    }
}

impl fmt::Display for HtmlFragment {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0
            .iter()
            .try_for_each(|node| fmt::Display::fmt(node, f))
    }
}

#[cfg(feature = "rocket")]
impl<'r> rocket::response::Responder<'r, 'static> for HtmlFragment {
    fn respond_to(
        self,
        req: &'r rocket::request::Request<'_>,
    ) -> rocket::response::Result<'static> {
        rocket::response::content::RawHtml(self.to_string()).respond_to(req)
    }
}

#[cfg(feature = "axum")]
impl axum::response::IntoResponse for HtmlFragment {
    fn into_response(self) -> axum::response::Response {
        axum::response::Html(self.to_string()).into_response()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_serializes() {
        let mut body = ElementData::new("body".to_string());

        let text = Node::Text("Hello, Rust!".into());
        body.add_child(text);

        let mut div = ElementData::new("div".to_string());
        div.set_attribute("class".to_string(), "container".to_string());

        let inner_text = Node::Text("This is inside a div.".into());
        div.add_child(inner_text);

        body.add_child(Node::Element(div));

        let document = Node::Element(body);

        assert_eq!(
            document.to_string(),
            "<body>Hello, Rust!<div class=\"container\">This is inside a div.</div></body>"
        )
    }
}
